[workspace]
resolver = "2"
members = [
    "src/termstorage-protocol",
    "src/termstorage-term",
    "src/termstorage-server",
    "src/termstorage-client",
]

[workspace.dependencies]
byteorder = "1.4.3"
